### ISSUE TITLE
Provide utility to package class files into JAR

### ISSUE THREAD

**Issue by rahulmutt** [rahulmutt/ghcvm#10]
### Motivation
Currently, `ghcvm` has a dependency on `libzip` (transitive from the `hs-java` dependency) which is making it difficult to build (see #7).

### Implementation
Write a utility module that can JAR class files together, making use of the pure Haskell library [zip](https://github.com/mrkkrp/zip).

**Comment by ExcaliburZero** [comment]
If you don't mind, I'd like to take a try at implementing this. I'm a little bit of a Haskell novice, but I've taken a look over the zip library, and I think I should be able to implement JAR file creation with it.

**Comment by rahulmutt** [comment]
Sure! Always happy to have more contributors :) Let me know if you need any help in integrating your changes.


  
  



‎

**Comment by puffnfresh** [comment]
@ExcaliburZero I could use the same library for something else I'm working on. Happy to help out!

**Comment by ExcaliburZero** [comment]
From what I have managed to put together so far, it looks like I can put together a module with a function to create an empty archive at a given FilePath, and a function to add a ByteString as a file into an existing archive.

The main thing that I am unsure of though is dealing with special cases. Though I'll work a bit more on refining what I have, and see where to go from there.

Here is what I have so far: https://github.com/ExcaliburZero/zip-jar-haskell/blob/testing/src/Lib.hs#L13-L60

**Comment by ExcaliburZero** [comment]
I have manged to put together this small module with a function for creating an empty jar and a function for adding a bytestring as a file into an existing jar.

https://github.com/ExcaliburZero/zip-jar-haskell/blob/25ea1036299dec8187a0a6e265041c00ff3ff2ff/src/Lib.hs

Can you give me some feedback on the module and it's functions?

Here is a small example application I put together which makes use of the functions to create a new jar containing a test file.

https://github.com/ExcaliburZero/zip-jar-haskell/blob/25ea1036299dec8187a0a6e265041c00ff3ff2ff/app/Main.hs

I have tested out the functions I put together, and they can be used to creating a working jar from class files and meta info, which can be run via `java -jar JARNAME`.

**Comment by rahulmutt** [comment]
It's looking good so far! I really like the detailed documentation. I think I'll document the code generator in a similar format. Can you extend the API you've made with the support for the following features as well?

- _Adding multiple files at once_: Disk operations are slow and having to add the file one at a time might kill compiler performance on large projects. Most likely, I'll end up keeping all the class files generated by a given module in memory and then dump them onto disk as a jar all at once.
- _Merging many jar files_: In your own projects, each Haskell module will have a jar associated with it, but when importing Haskell libraries it's rather cumbersome. So when building a library, all the modules' jars should be merged into a single jar and libraries will be distributed as such.

**Comment by ExcaliburZero** [comment]
I think I should be able to implement adding multiple files at once and merging jar files. I know that the zip library has support for performing multiple file changes at once, it will just be a matter of figuring out how to use that functionality.

Though, for the merging of jar files, how do you want to handle the contents of the `META-INF` sub-directories of each of the jars? Should the contents of those directories be ignored when performing the merge?

**Comment by ExcaliburZero** [comment]
I've implemented a function which adds multiple files into a jar archive at once.

https://github.com/ExcaliburZero/zip-jar-haskell/blob/b22bc183c4eb3ae783b3ec6ecdba6a19ebfd3107/src/Lib.hs#L178

Just let me know how you want to handle `META-INF` directories when merging jars, and I can work on implementing the jar merging function.

**Comment by rahulmutt** [comment]
Thanks for the work so far! It's looking good. I'm not sure how to handle `META-INF` right now - will update you once I've researched it a bit. For now, ignore the `META-INF` directories and focus on merging the class files.

**Comment by rahulmutt** [comment]
@ExcaliburZero I merged your utility functions into the module `GHCVM.JAR` and the are being used in the final step of compiling a module in `GHCVM.DriverPipeline`. See 64de61d85cdf8b86847b2c4649032af2084c5e7e. I will close this for now and make a new issue later for when I have a good idea of how to handle the `META-INF` bit.
