### ISSUE TITLE
Implement better naming scheme for closures

### ISSUE THREAD

**Issue by rahulmutt** [rahulmutt/ghcvm#14]
Currently, the following function declarations
```haskell
module Test.Main where
putStrLn = ...

putstrln = ...
```
generate a class `test/Main$putStrLn.class` and `test/Main$putstrln.class` but JARs are case-insensitive so both of them clash and only one arbitrary class file gets chosen while the other disappears, yielding a NoClassDef error at runtime. The current naming scheme is GHC's Z-encoding, but we need to extend it to make sure two functions names that are equivalent modulo case produce names that are not equivalent modulo case.

The function `GHCVM.CodeGen.Name.nameText` is the central function which regulates naming for closure identifiers. Looking for a naming scheme that keeps the names clean.

**Comment by rahulmutt** [comment]
I came up with 'Positional Case Encoding'. It works like this:
'Apply' -> 'Apply1'
'ApPly' -> 'ApPly4'
'ApplY' -> 'ApplY6'
You number the position starting from the left with 1 and sum the value of the positions of the capital letters. This is able to distinguish identifiers that are equivalent modulo case while keeping the naming simple so that the mapping from Haskell function -> class is clear. Thoughts?

**Comment by meiersi** [comment]
What about 'APply' vs 'apPly'? Their case positions both sum up to 3. I
think you'd have to consider the positions of the capital cases as a
bitstring and encode that to an integer. A hex-based encoding might even be
preferable. What do you think?

Rahul Muttineni <notifications@github.com> schrieb am Mi., 7. Sep. 2016 um
04:43 Uhr:

**Comment by rahulmutt** [comment]
Thanks for bringing that up, @meiersi! The easiest way is just to append the base36-encoded uniques (the unique integer id for a Haskell identifier) at the end. I was looking for something cleaner but I guess it'd be tough. Not that people are gonna be staring at the classes GHCVM generates anyways :)

**Comment by rahulmutt** [comment]
We decided that the case we're trying to make work is quite rare and not worth obfuscating class names that much. We should instead warn the user not to select such names #31.
