### ISSUE TITLE
Foreign exports

### ISSUE THREAD

**Issue by rahulmutt** [rahulmutt/ghcvm#35]
While foreign imports allow us to call java functions from within Haskell in a type-safe way, foreign exports allow us to export a Haskell function that can be called as a java function. More specifically, to accommodate the way Java frameworks are managed, we should allow existing classes to be subclasses within Haskell itself and implement interfaces. The alternative would be to roll out your own subclass and make each method call an exported Haskell function which would be unnecessary boilerplate.

Example of instance methods:
```haskell
data {-# CLASS "mypackage.SomeClass" #-} SomeClass = SomeClass (Object# SomeClass)
 
someMethod :: Int -> Java SomeClass ()
someMethod = ...

foreign export java someMethod :: Int -> Java SomeClass ()
```
This will create a new class with name "SomeClass.class" and with a method called "void someMethod(int)" which takes an int and returns void.

```haskell
add :: Int -> Int -> Int
add = ...

foreign export java add :: Int -> Int -> Int
```
This will statically export "int add(int, int)" as a static method of the current class.

**Comment by carymrobbins** [comment]
So a type defined as `Java c r` will be an instance method for a Java class `c` and will return `r`?  You may also wish to provide a pragma to signal an `@Override` modifier.  Maybe something like

```haskell
{-# JAVA_ANN "@Override" #-}
someMethod :: Int -> Java SomeClass ()
```

would generate

```java
@Override
public void someMethod(int var1)
```

**Comment by rahulmutt** [comment]
Not too sure if the @Override annotation specifically needs support since we could write an external tool to give your warnings about overriding a superclass method/making sure you're implementing all the abstract methods. 

But in general, yes, we do need some way of specifying annotations because some frameworks use those. Since we generate .class files directly, we can only support annotations with retention CLASS and RUNTIME. @Override has retention policy SOURCE so it's actually impossible for us to support it directly.

Since annotations are an "add-on" to the core issue, I'll create a new issue and we can continue our discussion there. See #48.

**Comment by rahulmutt** [comment]
Done with #72

**Comment by NCrashed** [comment]
Just to note, the current implementation fails on the:
``` haskell
import Primes
import GHC.Base

foreign export java takePrime :: Int -> Java a Int

takePrime i = return . fromIntegral $ primes !! i

primes = filterPrime [2..]
  where filterPrime (p:xs) =
          p : filterPrime [x | x <- xs, x `mod` p /= 0]
```

With:
```
ghcvm: panic! (the 'impossible' happened)
  (GHCVM version 0.0.1):
	No type variables for the Java foreign export!
```

**Comment by rahulmutt** [comment]
@NCrashed This is intended behaviour, although the error message could be better and should not be a panic. I'll file a new issue on this. 

Also, whenever an old issue hasn't been fully resolved, but has been closed, please file a new issue mentioning the old one - it's easy for me to lose track of new comments on closed issues.
