### ISSUE TITLE
Rewrite CodeGen monad

### ISSUE THREAD

**Issue by rahulmutt** [rahulmutt/ghcvm#5]
### Motivation
After discussion with @aloiscochard and his eagerness to provide support from the JVM assembler side, I have decided to depend on his [kuna](https://github.com/aloiscochard/kuna) project instead of `hs-java`.

### Implementation
1. Observe the structure of `kuna` and how the currently existing parts of the code generator can be rewritten in `kuna` style. This exploration should happen on a separate branch called `wip/kuna`. 

2. Remove the dependency of the `CodeGen` monad on the `GenerateIO` monad from the `hs-java` library.

3. Rewrite the existing parts of the codegen with the new `kuna`-based monad.

**Comment by aloiscochard** [comment]
I have extracted the bytecode assembler in a dedicated project `codec-jvm`:
https://github.com/aloiscochard/codec-jvm

There is a few change I wanna do first, and then I'll investigate `ghcvm` source to see what features are missing in `codec-jvm`, list them and implement them.

**Comment by rahulmutt** [comment]
Great work! I'll save you some time and list out the features I'm using right now:

**Features In Use Now**
- _Support for easy generation of inner classes_ It would be great if you could expose a convenient API for this.
- _Support for declaration/initialization of instance/static fields_ There should be a way to initialize fields in a composable way. Like I can declare a field specifying the initialization code, assuming that the reference to the 'this' object is in the operand stack, or something along those lines. Once the code is generated, all the initialization code for each of the fields is merged by running the monad.
-_Automatic calculation of maximum stack size/local variable array size (Optional)_ This is a nice-to-have and not required. I partially do calculation of maximum stack size with the `combineStackSize` function when merging blocks of JVM bytecodes.

Both of these are extremely important for the first version of the code generator. Check out `hs-java/JVM/Builder/Monad.hs` for current implementations of the above.

**Comment by rahulmutt** [comment]
This is done as of 64de61d85cdf8b86847b2c4649032af2084c5e7e. Inner classes are not really required, but later it would be nice to have the attributes written to the classfiles so that the Java interaction will look nice.
