### ISSUE TITLE
Foreign export VerifyError Operand stack underflow

### ISSUE THREAD

**Issue by NCrashed** [rahulmutt/ghcvm#76]
Commit: cfd5914690d56913429432d2c1ca32d53d12b2fd

Haskell side:
``` haskell
{-# LANGUAGE MagicHash #-}
module Export where

import Primes
import GHC.Base

data {-# CLASS "hello.Export" #-} Export = Export (Object# Export)

foreign export java takePrime :: Int -> Java Export Int

takePrime i = return . fromIntegral $ primes !! i

module Primes where

primes = filterPrime [2..]
  where filterPrime (p:xs) =
          p : filterPrime [x | x <- xs, x `mod` p /= 0]
```

Java side:
``` Java
import hello.Export;

public class HelloWorld {
    public static void main(String[] args) {
        String v = Integer.toString(new Export().takePrime(1));
        System.out.println(v);
    }
}
```

Error:
```
java.lang.VerifyError: Operand stack underflow
Exception Details:
  Location:
    hello/Export.takePrime(I)I @31: getfield
  Reason:
    Attempt to pop empty stack.
  Current Frame:
    bci: @31
    flags: { }
    locals: { 'hello/Export', integer }
    stack: { }
  Bytecode:
    0x0000000: b800 182a bb00 1a59 b200 20bb 000b 591b
    0x0000010: b700 23b7 0026 b800 2ab4 002e b800 32b4
    0x0000020: 0035 c000 0bb4 0039 ac                 
```

**Comment by rahulmutt** [comment]
Thanks for testing this out! I fixed the error as of 8b217c5. 

Because the GHCVM RTS is stateful, you need to initialise it before using an foreign exports. (The RTS needs to know whether you want to use the threaded RTS or not, to tune other parameters like stack size, etc.). I have modified your example to show how initialisation is done. You need only perform the initialisation once per run of your application if you use any exports. I'll mention this in the documentation.

```java
import ghcvm.runtime.Rts;
import ghcvm.runtime.RtsConfig;

import hello.Export;

public class HelloWorld {
    public static void main(String[] args) {
        Rts.hsInit(new String[0], RtsConfig.getDefault());
        String v = Integer.toString(new Export().takePrime(100));
        System.out.println(v);
    }
}
```

**Comment by rahulmutt** [comment]
Let me know if this is fixed on your side, so I can close it. Just out of curiosity, how did you perform the build of your example?

**Comment by NCrashed** [comment]
Thank you! I will check it out in an hour. 

I compiled my example with `cabalvm build` for haskell side. The Java side is built with IntelliJ IDEA. It should built it with `javac`, I suppose.

Here the generated `.cabal` file:
``` cabal
-- Initial hello.cabal generated by cabal init.  For further documentation,
--  see http://haskell.org/cabal/users-guide/

name:                hello
version:             0.1.0.0
-- synopsis:
-- description:
-- license:
license-file:        LICENSE
author:              Anton Gushcha
maintainer:          ncrashed@gmail.com
-- copyright:
-- category:
build-type:          Simple
-- extra-source-files:
cabal-version:       >=1.10

library
  other-modules:
    Primes
    Export
  other-extensions:    CPP, MagicHash, NoImplicitPrelude, UnboxedTuples, BangPatterns, UnliftedFFITypes, GHCForeignImportPrim, Trustworthy, DeriveGeneric, StandaloneDeriving, MultiParamTypeClasses, FlexibleInstances, UndecidableInstances, AllowAmbiguousTypes, TypeFamilies, RoleAnnotations, Safe, Unsafe, GeneralizedNewtypeDeriving, AutoDeriveTypeable, ScopedTypeVariables, PolyKinds, RankNTypes, TypeOperators, GADTs, DeriveDataTypeable, EmptyCase, DataKinds, ExplicitNamespaces, DeriveTraversable, ConstraintKinds, CApiFFI, NondecreasingIndentation, ExistentialQuantification, NegativeLiterals, RecordWildCards, ExplicitForAll, FunctionalDependencies, KindSignatures, TypeSynonymInstances, FlexibleContexts, ParallelArrays, DeriveFunctor, TupleSections, OverloadedStrings, NamedFieldPuns, DeriveFoldable, InstanceSigs, PatternSynonyms, ForeignFunctionInterface, DefaultSignatures, PatternGuards
  build-depends:
      base >=4.8 && <4.9
    , ghc-prim >=0.4 && <0.5
    , reflex

  hs-source-dirs:      src
  build-tools:         hsc2hs, alex, happy
  default-language:    Haskell2010
```

**Comment by rahulmutt** [comment]
I had to build manually using javac and manage the classpath myself - it was a tad painful :) It's good to know that you can easily plug it in to IntelliJ and build. So you just included the .jar that was generated by cabalvm inside IntelliJ?

**Comment by NCrashed** [comment]
I use gradle to add all compiled jars (rts, base, ghc-prims, integer and app jars) to classpath:
```
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar', '*.so'])
}
```

To be honest, the hello java app is not actually the app I originally got the error from. I am trying to plug the haskell jars into minecraft (yep, hilarious) to make first haskell mod for the game.

**Comment by rahulmutt** [comment]
Wow that is cool! Please let me know how that goes, I want to hear about it. Specifically things like performance/any new features that can make your job easier.

**Comment by NCrashed** [comment]
Ok, I will ping you when I succeeded (or stuck on some problem as below). 

I made a `./cleaninstall.sh` with the latest master and it now doesn't generate `hello.Export` module in the output jar at all.

**Comment by rahulmutt** [comment]
I'm not able to reproduce that. Can you do a dump of the contents of the jar file and link me to it? Also let me know your CabalVM setup like the .cabal file (which I presume is just what you mentioned previously) and the exact commands you used to build your project.

**Comment by NCrashed** [comment]
https://github.com/NCrashed/hello-ghcvm/tree/8408829b796c3fec4950e2e0eb8f5a1968b21c4d

There the `compile.sh` and `HShello-0.1.0.0.jar` that was produced. 

Also I am going to try to cleanup all ghcvm global installation and start from scratch to test it out.

**Comment by rahulmutt** [comment]
You do have hello.Export, except the real name is: `hellozm0zi1zi0zi0.Export` - Try importing that? It's not desired behaviour so I'll see what's causing it.

**Comment by rahulmutt** [comment]
Nevermind, that refers to something else. You're getting that special case since you're building a `library` target. For an `executable` target you won't get the error, as long as you explicitly specify the right `main` class, which I think `java` forces you to do anyways. This is unintended behaviour - I'll file a new issue for this.

**Comment by rahulmutt** [comment]
I opened #80 to document the problem.

**Comment by NCrashed** [comment]
> You do have hello.Export, except the real name is: hellozm0zi1zi0zi0.Export - Try importing that? 

I tried, but the module doesn't have a cozy method to call, only raw STG closures. 

I cleaned up `ghcvm-pkg` database, deleted `~/.cabalvm` and `~/.local/bin`, redownloaded the repo and made `./install.sh`. And it now includes the exported modules to output jar for library target. 

Now I faced new problem, when I call the exported method:
```
java.lang.NoClassDefFoundError: ghczmprim/ghc/Types
	at base.ghc.Base.<clinit>(Unknown Source) ~[Base.class:?]
	at hellozm0zi1zi0zi0.Export$zdfstableZZC0ZZChellozzm0zzi1zzi0zzi0ZZCExportZZCsayHello3.thunkEnter(Unknown Source) ~[Export$zdfstableZZC0ZZChellozzm0zzi1zzi0zzi0ZZCExportZZCsayHello3.class:?]
	at ghcvm.runtime.thunk.StgIndStatic.enter(StgIndStatic.java:30) ~[StgIndStatic.class:?]
	at ghcvm.runtime.thunk.StgThunk.apply(StgThunk.java:117) ~[StgThunk.class:?]
	at ghcvm.runtime.apply.Apply$8.enter(Apply.java:75) ~[Apply$8.class:?]
	at hellozm0zi1zi0zi0.Export$zdfstableZZC0ZZChellozzm0zzi1zzi0zzi0ZZCExportZZCsayHello.enter(Unknown Source) ~[Export$zdfstableZZC0ZZChellozzm0zzi1zzi0zzi0ZZCExportZZCsayHello.class:?]
	at ghcvm.runtime.apply.StgFun.apply(StgFun.java:116) ~[StgFun.class:?]
	at ghcvm.runtime.apply.Apply$8.enter(Apply.java:75) ~[Apply$8.class:?]
	at ghcvm.runtime.thunk.Ap2Upd.thunkEnter(Ap2Upd.java:21) ~[Ap2Upd.class:?]
	at ghcvm.runtime.thunk.StgInd.enter(StgInd.java:19) ~[StgInd.class:?]
	at ghcvm.runtime.stg.StgClosure.evaluate(StgClosure.java:20) ~[StgClosure.class:?]
	at ghcvm.runtime.stg.StgEnter.stackEnter(StgEnter.java:15) ~[StgEnter.class:?]
	at ghcvm.runtime.stg.StackFrame.enter(StackFrame.java:43) ~[StackFrame.class:?]
	at ghcvm.runtime.stg.StackFrame.enter(StackFrame.java:26) ~[StackFrame.class:?]
	at ghcvm.runtime.stg.StackFrame.enter(StackFrame.java:26) ~[StackFrame.class:?]
	at ghcvm.runtime.stg.StackFrame.enter(StackFrame.java:26) ~[StackFrame.class:?]
	at ghcvm.runtime.stg.Capability.schedule(Capability.java:245) ~[Capability.class:?]
	at ghcvm.runtime.RtsScheduler.scheduleWaitThread(RtsScheduler.java:57) ~[RtsScheduler.class:?]
	at ghcvm.runtime.Rts.evalJava(Rts.java:104) ~[Rts.class:?]
	at hello.Export.sayHello(Unknown Source) ~[Export.class:?]
```

Build artifacts I uploaded to the:
https://github.com/NCrashed/hello-ghcvm/tree/dc69bf01d4d6f4e7828b5ac9d2a18922a3fea225

I see that `HSghc-prim-0.4.0.0.jar` has different name `ghczmprim.ghc` for module that is expected by `hello` jar `ghczmprim/ghc`.

**Comment by rahulmutt** [comment]
How are you performing the execution - what flags are you sending `java`? It looks like a classpath problem to me. You need to make sure that you point to the `ghc-prim` jar. If you don't want to deal with all those issues, use an `executable` target which will create an uberjar.

**Comment by NCrashed** [comment]
I created minimal example where I call `javac` by hands, and it works!

https://github.com/NCrashed/hello-ghcvm/commit/13d15542c83c8357aff2f7e2ff1162340453b934

That amazing, it works! So, the issue is now in Idea to force it to include the jar not only at building phase but at runtime too. I think, the issue is resolved now. Thank you for amazing project!

P.S. I will ping you in gitter when I ready with full MC mod.

**Comment by rahulmutt** [comment]
Awesome! Looking forward to hearing about it. Will close the issue then.
