### ISSUE TITLE
The time library doesn't work at a particular time

### ISSUE THREAD

**Issue by psibi** [rahulmutt/ghcvm#82]
This is a weird bug which I think depends upon some time. (Note that this is my guess, I maybe completely wrong.) Filing here for recording this scenario.

For the past half hour or so, I was getting hit up with this error while building the `time` package:

```
root@870c574bbf3a:/time-1.6.0.1# cabalvm build
Package has never been configured. Configuring with default flags. If this
fails, please run configure manually.
Resolving dependencies...
Configuring time-1.6.0.1...
Building time-1.6.0.1...
Preprocessing library time-1.6.0.1...
[ 1 of 26] Compiling Data.Time.Clock.CTimespec ( dist/build/Data/Time/Clock/CTimespec.hs, dist/build/Data/Time/Clock/CTimespec.jar )
[ 2 of 26] Compiling Data.Time.Clock.CTimeval ( lib/Data/Time/Clock/CTimeval.hs, dist/build/Data/Time/Clock/CTimeval.jar )
ghcvm: panic! (the 'impossible' happened)
  (GHCVM version 0.0.1):
        Prelude.head: empty list

Please report this as a GHCVM bug: http://github.org/rahulmutt/ghcvm/issues
```

I was able to reproduce this scenario both in my docker environment as well as my machine. Then after a while, it started working automatically (again in both the environments).

**Comment by psibi** [comment]
This error has started appearing again.

**Comment by psibi** [comment]
Ah, it doesn't depend upon the time (Unfotunate, since the title of the issue was nice!).

The time library builds fine in ghcvm commit: 596e848b4e79110decdaa107e53da954225c081e

It fails in the latest master branch: e70340320b2cb9cd618527d6668b77502f044743

We need to add tests soon for all the current packages that are ported. I will try to add that to Travis ASAP.

**Comment by psibi** [comment]
I wrote a hacky test script and it seems to be building there: https://travis-ci.org/psibi/ghcvm/builds/168429034

I guess then I'm missing something in my system. I will debug it tomorrow.

**Comment by rahulmutt** [comment]
Fixed the build with the recent patch change in `ghcvm-hackage`. Run `cabalvm update` to make the change visible.
