### ISSUE TITLE
Proposal: Have packages.json in ghcvm-hackage containing packages list

### ISSUE THREAD

**Issue by psibi** [rahulmutt/ghcvm#86]
Currently there are two types of packages that work with ghcvm:
1. Ported Packages: Packages which has been specifically ported for
   ghcvm and which contain modified patches (and possibly a new cabal
   file) in ghcvm-hackage.
2. UnPorted Packages (Any better naming suggestions?): Unported but
   working packages with ghcvm because it's dependencies may already
   have been ported. Example: fibonacci package.

The `packages.json` file will have two keys (ported & unported) which
will contain the list of respective packages. We will ultimately use
this `packages.json` in our test script.

**Comment by psibi** [comment]
I will go and implement this, if folks here agree.

**Comment by rahulmutt** [comment]
The proposal looks good. Some alternatives for naming: Modified/Normal, Patched/Vanilla.

**Comment by psibi** [comment]
I like Patched/Vanilla. I will go with that.

**Comment by psibi** [comment]
Closing the issue since it's been fixed in ghcvm-hackage.
